version: '3'
services:
  web:
    build: .
    ports:
    - "8888:8888"
  http:
    image: nginx:alpine
    ports:
    - "443:443"
    - "80:80"
    volumes:
    - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    - "./nginx/servername.crt:/etc/nginx/servername.crt"
    - "./nginx/crt.key:/etc/nginx/crt.key"
    depends_on:
    - web